### ISSUE TITLE
Elemental638 needs to be green, not blue

### ISSUE THREAD

**Issue by kenorb** [Ecilos/ecilos-unity-assets-avatars#2]

**Comment by Mivadour** [comment]
![L_initialShadingGroup_BaseColor 1001](https://user-images.githubusercontent.com/115797568/218188928-552e5c55-3483-42de-8a90-316fdf775f86.jpg)
![L_initialShadingGroup_BaseColor 1002](https://user-images.githubusercontent.com/115797568/218188929-ac16382d-8f2f-450d-a4c9-d3601e34c348.jpg)
![L_initialShadingGroup_BaseColor 1003-Leaves_BaseColor_1003-Leav](https://user-images.githubusercontent.com/115797568/218188930-a742daa9-711d-450f-9857-8b7d080d4260.png)
![L_initialShadingGroup_Emissive 1001](https://user-images.githubusercontent.com/115797568/218188934-b1ad5e7e-c2db-4bea-9b68-378e09a157f1.jpg)
![L_initialShadingGroup_Emissive 1002](https://user-images.githubusercontent.com/115797568/218188935-aff3521a-58a2-4342-b830-9feaa4b2e308.jpg)

**Comment by kenorb** [comment]
<img width="382" alt="image" src="https://user-images.githubusercontent.com/266306/218262702-524dd24c-6230-4c8b-a2b7-6fc784f4798e.png">

Thank you.
