### ISSUE TITLE
Elemental631 needs to be red, like a fire

### ISSUE THREAD

**Issue by kenorb** [Ecilos/ecilos-unity-assets-avatars#3]
It's a fire elemental.

**Comment by Mivadour** [comment]
![BaseColor](https://user-images.githubusercontent.com/115797568/218198167-f956c6a3-8181-433d-a4c2-30dc05b2a04c.jpg)
![Emissive](https://user-images.githubusercontent.com/115797568/218198173-7af85c04-3da5-4103-87c6-8632fb5a4bb8.jpg)
![how it looks](https://user-images.githubusercontent.com/115797568/218198177-219d121f-b0a1-408e-b6b9-f6101254a7fc.jpg)

**Comment by Mivadour** [comment]
![BaseColor](https://user-images.githubusercontent.com/115797568/218198971-ce5d8fc5-f650-46bb-90cb-63baf8b2e0eb.jpg)
![Emissive](https://user-images.githubusercontent.com/115797568/218198974-40c023bf-3a09-4d96-8669-47c793bc1a6f.jpg)
![how it looks](https://user-images.githubusercontent.com/115797568/218198977-fc694d38-ea58-476a-aeaf-82bed7293f7f.jpg)

**Comment by Mivadour** [comment]
![OcclusionRoughnessMetallic](https://user-images.githubusercontent.com/115797568/218202150-e3e6f09e-99fc-4d27-9c3b-eb68497adbbc.jpg)

**Comment by kenorb** [comment]
![Screenshot 2023-02-11 at 15 00 09 png](https://user-images.githubusercontent.com/266306/218265659-e37b60f2-36e2-407c-92f4-2a0a15ed53e3.jpg)
![Screenshot 2023-02-11 at 15 00 16 png](https://user-images.githubusercontent.com/266306/218265661-3ad21731-848f-4a8a-b960-0b39c78babd1.jpg)
![Screenshot 2023-02-11 at 15 00 23 png](https://user-images.githubusercontent.com/266306/218265662-e864df8b-aca7-48c0-a27a-8d9b2b1272bc.jpg)
